// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using japan_dashboard_api.Store;

namespace japan_dashboard_api.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20191124182125_init")]
  partial class init
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.0.1");

      modelBuilder.Entity("japan_dashboard_api.Models.Prefecture", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<string>("iso")
                      .HasColumnType("TEXT");

            b.Property<string>("prefectureEn")
                      .HasColumnType("TEXT");

            b.Property<string>("prefectureJp")
                      .HasColumnType("TEXT");

            b.Property<string>("region")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Prefectures");
          });

      modelBuilder.Entity("japan_dashboard_api.Models.PrefecturePopulation", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<string>("age")
                      .HasColumnType("TEXT");

            b.Property<string>("gender")
                      .HasColumnType("TEXT");

            b.Property<string>("population")
                      .HasColumnType("TEXT");

            b.Property<string>("prefectureIso")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("PrefecturePopulations");
          });
#pragma warning restore 612, 618
    }
  }
}
